package com.fudn;

public enum ResultCode {
    SUCCESS,
    INVALID_INPUT,

    INVALID_USERNAME,
    DUPLICATE_USERNAME,
    INVALID_EMAIL,
    DUPLICATE_EMAIL,
    WEAK_PASSWORD,
    PASSWORD_MISMATCH,
    UNDERAGE,
    INVALID_PHONE,

    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,

    USER_NOT_FOUND,
    OLD_PASSWORD_INCORRECT,
    SAME_AS_OLD_PASSWORD,
    PASSWORD_REUSED,
    INVALID_TOKEN;

    public boolean isSuccess() {
        return this == SUCCESS;
    }
}